GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxiZXJ0IiwiaWF0IjoxNjQ0Mjk4OTcxLCJleHAiOjE2NDQyOTkwMzZ9.g6A2AfWmxS1D2Hl_P6jndTgvLBI9xO5gBfxhMQQkVaw

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxiZXJ0IiwiaWF0IjoxNjQ0Mjk4ODk5fQ.crMmduPhu1yTZDmhJ3XCxKCHK4UC4uoxR-6rxufufoA"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxiZXJ0IiwiaWF0IjoxNjQ0Mjk4ODk5fQ.crMmduPhu1yTZDmhJ3XCxKCHK4UC4uoxR-6rxufufoA"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Albert"
}